### ISSUE TITLE
Erros

### ISSUE THREAD

**Issue by BMasquio** [alerj/tribunais#10]
[2019-12-09 00:01:05] dusk.ERROR: Curl error thrown for http POST to /session/3aae3f52f023e3d7ab56cc3dbd4960eb/url with params: {"url":"http:\/\/www4.tjrj.jus.br\/ConsultaUnificada\/consulta.do"}

Operation timed out after 30001 milliseconds with 0 bytes received {"exception":"[object] (Facebook\\WebDriver\\Exception\\WebDriverCurlException(code: 0): Curl error thrown for http POST to /session/3aae3f52f023e3d7ab56cc3dbd4960eb/url with params: {\"url\":\"http:\\/\\/www4.tjrj.jus.br\\/ConsultaUnificada\\/consulta.do\"}

Operation timed out after 30001 milliseconds with 0 bytes received at /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:297)
[stacktrace]
#0 /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(565): Facebook\\WebDriver\\Remote\\HttpCommandExecutor->execute(Object(Facebook\\WebDriver\\Remote\\WebDriverCommand))
#1 /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php(40): Facebook\\WebDriver\\Remote\\RemoteWebDriver->execute('get', Array)
#2 /var/www/tribunais/vendor/facebook/webdriver/lib/WebDriverNavigation.php(85): Facebook\\WebDriver\\Remote\\RemoteExecuteMethod->execute('get', Array)
#3 /var/www/tribunais/vendor/laravel/dusk/src/Browser.php(139): Facebook\\WebDriver\\WebDriverNavigation->to('http://www4.tjr...')
#4 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(50): Laravel\\Dusk\\Browser->visit('http://www4.tjr...')
#5 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(137): App\\Services\\Scrapers\\TjRj\\Scraper->__scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#6 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(152): App\\Services\\Scrapers\\TjRj\\Scraper->scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#7 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): App\\Services\\Scrapers\\TjRj\\Scraper->App\\Services\\Scrapers\\TjRj\\{closure}(Object(App\\Data\\Models\\SearchTerm), 0)
#8 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(155): Illuminate\\Support\\Collection->each(Object(Closure))
#9 /var/www/tribunais/routes/console.php(19): App\\Services\\Scrapers\\TjRj\\Scraper->scrape()
#10 [internal function]: Illuminate\\Foundation\\Console\\ClosureCommand->{closure}()
#11 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Object(Closure), Array)
#12 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(78): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#14 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#15 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/ClosureCommand.php(55): Illuminate\\Container\\Container->call(Object(Closure), Array)
#16 /var/www/tribunais/vendor/symfony/console/Command/Command.php(255): Illuminate\\Foundation\\Console\\ClosureCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/tribunais/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/tribunais/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ClosureCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/tribunais/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/tribunais/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"}
[2019-12-09 04:01:05] dusk.ERROR: Curl error thrown for http POST to /session/ead5486a7794bfdd167829cf00831256/url with params: {"url":"http:\/\/www4.tjrj.jus.br\/ConsultaUnificada\/consulta.do"}

Operation timed out after 30000 milliseconds with 0 bytes received {"exception":"[object] (Facebook\\WebDriver\\Exception\\WebDriverCurlException(code: 0): Curl error thrown for http POST to /session/ead5486a7794bfdd167829cf00831256/url with params: {\"url\":\"http:\\/\\/www4.tjrj.jus.br\\/ConsultaUnificada\\/consulta.do\"}

Operation timed out after 30000 milliseconds with 0 bytes received at /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:297)
[stacktrace]
#0 /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(565): Facebook\\WebDriver\\Remote\\HttpCommandExecutor->execute(Object(Facebook\\WebDriver\\Remote\\WebDriverCommand))
#1 /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php(40): Facebook\\WebDriver\\Remote\\RemoteWebDriver->execute('get', Array)
#2 /var/www/tribunais/vendor/facebook/webdriver/lib/WebDriverNavigation.php(85): Facebook\\WebDriver\\Remote\\RemoteExecuteMethod->execute('get', Array)
#3 /var/www/tribunais/vendor/laravel/dusk/src/Browser.php(139): Facebook\\WebDriver\\WebDriverNavigation->to('http://www4.tjr...')
#4 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(50): Laravel\\Dusk\\Browser->visit('http://www4.tjr...')
#5 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(137): App\\Services\\Scrapers\\TjRj\\Scraper->__scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#6 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(152): App\\Services\\Scrapers\\TjRj\\Scraper->scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#7 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): App\\Services\\Scrapers\\TjRj\\Scraper->App\\Services\\Scrapers\\TjRj\\{closure}(Object(App\\Data\\Models\\SearchTerm), 0)
#8 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(155): Illuminate\\Support\\Collection->each(Object(Closure))
#9 /var/www/tribunais/routes/console.php(19): App\\Services\\Scrapers\\TjRj\\Scraper->scrape()
#10 [internal function]: Illuminate\\Foundation\\Console\\ClosureCommand->{closure}()
#11 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Object(Closure), Array)
#12 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(78): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#14 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#15 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/ClosureCommand.php(55): Illuminate\\Container\\Container->call(Object(Closure), Array)
#16 /var/www/tribunais/vendor/symfony/console/Command/Command.php(255): Illuminate\\Foundation\\Console\\ClosureCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/tribunais/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/tribunais/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ClosureCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/tribunais/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/tribunais/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"}
[2019-12-09 08:01:05] dusk.ERROR: Curl error thrown for http POST to /session/41e3c7e0f45d3e11f1c0ea60b85d18be/url with params: {"url":"http:\/\/www4.tjrj.jus.br\/ConsultaUnificada\/consulta.do"}

Operation timed out after 30002 milliseconds with 0 bytes received {"exception":"[object] (Facebook\\WebDriver\\Exception\\WebDriverCurlException(code: 0): Curl error thrown for http POST to /session/41e3c7e0f45d3e11f1c0ea60b85d18be/url with params: {\"url\":\"http:\\/\\/www4.tjrj.jus.br\\/ConsultaUnificada\\/consulta.do\"}

Operation timed out after 30002 milliseconds with 0 bytes received at /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:297)
[stacktrace]
#0 /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php(565): Facebook\\WebDriver\\Remote\\HttpCommandExecutor->execute(Object(Facebook\\WebDriver\\Remote\\WebDriverCommand))
#1 /var/www/tribunais/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php(40): Facebook\\WebDriver\\Remote\\RemoteWebDriver->execute('get', Array)
#2 /var/www/tribunais/vendor/facebook/webdriver/lib/WebDriverNavigation.php(85): Facebook\\WebDriver\\Remote\\RemoteExecuteMethod->execute('get', Array)
#3 /var/www/tribunais/vendor/laravel/dusk/src/Browser.php(139): Facebook\\WebDriver\\WebDriverNavigation->to('http://www4.tjr...')
#4 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(50): Laravel\\Dusk\\Browser->visit('http://www4.tjr...')
#5 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(137): App\\Services\\Scrapers\\TjRj\\Scraper->__scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#6 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(152): App\\Services\\Scrapers\\TjRj\\Scraper->scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#7 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): App\\Services\\Scrapers\\TjRj\\Scraper->App\\Services\\Scrapers\\TjRj\\{closure}(Object(App\\Data\\Models\\SearchTerm), 0)
#8 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(155): Illuminate\\Support\\Collection->each(Object(Closure))
#9 /var/www/tribunais/routes/console.php(19): App\\Services\\Scrapers\\TjRj\\Scraper->scrape()
#10 [internal function]: Illuminate\\Foundation\\Console\\ClosureCommand->{closure}()
#11 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Object(Closure), Array)
#12 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(78): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#14 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#15 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/ClosureCommand.php(55): Illuminate\\Container\\Container->call(Object(Closure), Array)
#16 /var/www/tribunais/vendor/symfony/console/Command/Command.php(255): Illuminate\\Foundation\\Console\\ClosureCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#17 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /var/www/tribunais/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/tribunais/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ClosureCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/tribunais/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /var/www/tribunais/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"}
[2019-12-09 12:00:51] dusk.ERROR: Waited 10 seconds for text [Resultado da pesquisa]. {"exception":"[object] (Facebook\\WebDriver\\Exception\\TimeOutException(code: 0): Waited 10 seconds for text [Resultado da pesquisa]. at /var/www/tribunais/vendor/laravel/dusk/src/Concerns/WaitsForElements.php:261)
[stacktrace]
#0 /var/www/tribunais/vendor/laravel/dusk/src/Concerns/WaitsForElements.php(84): Laravel\\Dusk\\Browser->waitUsing(10, 100, Object(Closure), 'Waited %s secon...')
#1 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(57): Laravel\\Dusk\\Browser->waitForText(Array, 10)
#2 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(137): App\\Services\\Scrapers\\TjRj\\Scraper->__scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#3 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(152): App\\Services\\Scrapers\\TjRj\\Scraper->scrapeCourt('TJRJ', 'exmo sr preside...', 2019)
#4 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): App\\Services\\Scrapers\\TjRj\\Scraper->App\\Services\\Scrapers\\TjRj\\{closure}(Object(App\\Data\\Models\\SearchTerm), 0)
#5 /var/www/tribunais/app/Services/Scrapers/TjRj/Scraper.php(155): Illuminate\\Support\\Collection->each(Object(Closure))
#6 /var/www/tribunais/routes/console.php(19): App\\Services\\Scrapers\\TjRj\\Scraper->scrape()
#7 [internal function]: Illuminate\\Foundation\\Console\\ClosureCommand->{closure}()
#8 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Object(Closure), Array)
#9 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(78): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Object(Closure), Object(Closure))
#11 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Object(Closure), Array, NULL)
#12 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/ClosureCommand.php(55): Illuminate\\Container\\Container->call(Object(Closure), Array)
#13 /var/www/tribunais/vendor/symfony/console/Command/Command.php(255): Illuminate\\Foundation\\Console\\ClosureCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/tribunais/vendor/symfony/console/Application.php(921): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/tribunais/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Foundation\\Console\\ClosureCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/tribunais/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/tribunais/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/tribunais/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 {main}
"}

**Comment by BMasquio** [comment]
Já foi resolvido. Era um problema na pesquisa do site do TJ.
